### ISSUE TITLE
关于代码何时发布的问题

### ISSUE THREAD

**Issue by lidh15** [cloudyskyy/Guwen-UNILM#1]

**Comment by cloudyskyy** [comment]
您好，感谢您的提醒，将于5日内上传代码。之前由于本人升学、更换研究方向以及学校服务器更新等诸多因素没有更新仓库，对于您的困扰表示抱歉。预计4月21日前将上传并保证代码可以正常运行。

另：如果要follow古文翻译的相关句子级别数据集，这里向您推荐小牛翻译（东北大学NLP组）在两个月前开源的文言文-现代文平行语料，一共有967257个句对，地址在[文言文（古文）-现代文平行语料](https://github.com/NiuTrans/Classical-Modern)，与本文构建的数据集如出一辙，都为句子级语料，且规模在1000k左右，是我们的50k左右数据集规模的20倍左右。该数据集也可以直接使用我们Guwen-UNILM的代码运行。

**Comment by cloudyskyy** [comment]
您好，仓库已经更新在[Link](https://github.com/cloudyskyy/Guwen-UNILM)。
